### PR TITLE
Add dynamic callbacks

### PR DESCRIPTION
**Pull request by sebromero**
Adds the option of using lambda callbacks. Benefits: See documentation in readme file
Backwards compatible. This PR is based on https://github.com/ubidefeo/FTDebouncer/pull/7

### CODE REVIEW

**Review by ubidefeo — COMMENTED** [review]
Since I've been planning on introducing template based callbacks with an event system I'm not sure Lambda implementation fits at that point.
I might not see the benefit, help me getting it, @sbhklr :)

**Comment by sebromero** [comment]
Actually the PR name is a bit misleading. I should maybe call it dynamic callbacks as it's really not somuch about lambdas. But the point is to use a custom callback, not a prescribed function. The things is my implementation also supports classic function pointers. e.g. `pinDebouncer.addPin(3, HIGH, INPUT_PULLUP, ldrPinActivated);`
 
But to answer your question: I guess the reasons for not using a global function like `onPinActivated` or `onPinDeactivated` are obvious. The short answer is object orientation. 

- At the moment if someone wants to use multiple debouncer instances with different debouncing times there is no way to figure out in the call back which instance it was. Depending on the needs this may or may not be a problem.

- There's the chance of a name clash. If any other library uses the same function signature, the linker will fail which will be very hard to debug for beginners.
- if multiple pins are debounced the `onPinActivated` will become 🍝 .
```
void onPinActivated(int pinNr){
	if(pinNr == 2) {
		Serial.print("Pin activated: ");
		Serial.println(pinNr);
	} else if(pinNr == 3) {
		if(sensorActivated){
			if(sensordata > 128){
				//
			}
		}
	} else if(pinNr == 4) {
		//
	} else if(pinNr == 5){
		//
	}
}
```
- Closures allow to cohesively declare the callback logic together with the registration of the pin.
- Closures are a concept that people who have done a bit of JavaScript will understand. This makes it easy for them to use the library.
- Closure are imho easier to understand than functors and templates
- Closure can capture variables and that's probably the coolest things about it
- Closures are a language construct baked into the language and hence needs no imports and comes with very little overhead.
- Read here why lambdas are cool: https://www.cprogramming.com/c++11/c++11-lambda-closures.html

That said, introducing templates would actually be an easy addition to this code base as it builds on top. However I currently don't see how a template mechanism would help 🤔 What would be the thing to be templatized?

**Comment by sebromero** [comment]
Also read the section `Making Delegates with Lambdas`: https://www.cprogramming.com/c++11/c++11-lambda-closures.html

> This is a pretty standard pattern of allowing a callback function to be registered with a class when something interesting happens.

**Review by ubidefeo — APPROVED** [review]
@sebromero 
I finally got some time to look into this properly.
I like it a lot.
Please merge this one, we don't have a gazillion users who will hate us if anything breaks :D

**Pull request merged**
