### PR TITLE
Refactorings

### PR DESCRIPTION
**Pull request by sebromero**
Simplified and removed some duplicate code and applied some modern C++ style refactorings.
Please review.

### CODE REVIEW

**Review by ubidefeo — APPROVED** [review]

**Review by ubidefeo — APPROVED** [review]

**Review by ubidefeo — APPROVED** [review]
I still have to get used to some C++ things.
This is a nice one, thank you  :)

**Review by ubidefeo — APPROVED** [review]

**Review by ubidefeo — APPROVED** [review]

**Review by ubidefeo — APPROVED** [review]

**Review by ubidefeo — COMMENTED** [review]
I had used this in my first writing.
Won't it leave the last item out?

**Review by ubidefeo — APPROVED** [review]

**Review by ubidefeo — APPROVED** [review]
classy!

**Review by ubidefeo — APPROVED** [review]

**Review by ubidefeo — APPROVED** [review]
is this just a matter of style/best practices?

**Review by ubidefeo — APPROVED** [review]
Thank you for all this :)

**Comment by sebromero** [comment]
Piacere👌 For some reason I can't see where your comments point to but in general I applied some best practices that I learned during my studies. In terms of logic we should consider using a C++ unit testing framework to make the code change proof.

**Comment by ubidefeo** [comment]
Teach me about it :)

**Pull request merged**
