### PR TITLE
Spring cleaning

### PR DESCRIPTION
**Pull request by sebromero**
- Tidies up code formatting
- Adds documentation to methods
- Adds memory management for deconstruction to prevent memory leaks

### CODE REVIEW

**Review by ubidefeo — APPROVED** [review]
Thank you for making `::init()` and `::update()` aliases of `::begin()` and `::run()`.
I like that we can deprecated them with very little work besides a set of warnings (can you add some `#pragma` messages about depracation next?

**Comment by sebromero** [comment]
> Thank you for making `::init()` and `::update()` aliases of `::begin()` and `::run()`.
> I like that we can deprecated them with very little work besides a set of warnings (can you add some `#pragma` messages about depracation next?

I wonder if it's necessary to use old style `#pragma` messages? I've used the standardised and more modern `[[deprecated]]` syntax. See: https://en.cppreference.com/w/cpp/language/attributes/deprecated and here https://docs.microsoft.com/en-us/cpp/cpp/attributes?view=vs-2019

**Comment by ubidefeo** [comment]
I like this `[[deprecated]]` syntax!
I'll add it with some explanation text on the next release :)

**Comment by sebromero** [comment]
> I like this `[[deprecated]]` syntax!
> I'll add it with some explanation text on the next release :)

I've already added it, have you seen it? It's in the header file.

**Pull request merged**
